### PR TITLE
Universal APK - User Input to set IP address

### PR DESCRIPTION
**Pull request by bboyairwreck**
Eric, developer of PieMessage here. I have successfully created a universal APK for people to use. In theory, we can skip the need for testers to compile completely.
- No more need to edit Constants.java
- Added MainActivity that will show on first-time launch of app
- EditText that asks for OSX Client's IP address
- Added PreferenceActivity/Fragment to edit the IP Address preference

This has already been tested. I was able to switch between two Macbooks dynamically by editing IP address within the app's preference menu.

Let me know what you guys think. Gimme a thumbs up and I'll merge it.

### CODE REVIEW

**Comment by atomheartbrother** [comment]
Excited!

**Comment by KevDoy** [comment]
Will try this later. Thank you

**Comment by benjyyy** [comment]
where can i download it?

**Comment by benjyyy** [comment]
so where do i get the universal apk? =)

**Comment by anna1542** [comment]
ericChee-UniversalAPKWithIPAddressInput

**Comment by anna1542** [comment]
Hey

**Comment by anna1542** [comment]
994431

**Review by anna1542 — COMMENTED** [review]
Como obtendre el apk?

**Pull request merged**
