### PR TITLE
Added .gitignore and terminal compilation

### PR DESCRIPTION
**Pull request by saryana**
I don't think everyone needs access to the .idea and other IntelliJ specific files, it will slow down development with merge conflicts and weird issues with more people working on it. I added the terminal compilation since it can be a little heavy having multiple IDEs open and compiling the service. I didn't extensively test it and this is the first time I have used gradle from the ground up, but it was easy enough and tested the commands. The huge deletions were just because I needed to remove some of the out and .idea stuff in order to include it in the .gitignore.

### CODE REVIEW

**Comment by AlaricCalmette** [comment]
👍

**Comment by sgraden** [comment]
Should make process of setup simpler +1

**Comment by bboyairwreck** [comment]
Haha good call. Can @saryana &/or those who approved verify 100% that the project works and the instructions work as mentioned. After that I'll go ahead and merge it in

**Comment by bboyairwreck** [comment]
Aight. Looks good. Gonna go ahead and merge it in. Thanks @saryana

**Pull request merged**
